// todo_angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { AppService } from './app.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  newTodoString = '';

  todos: any = [];

  constructor(private appService: AppService) {}

  ngOnInit() {
    this.showTodo();
  }

  addTodo = () => {
    this.appService.addTodo(this.newTodoString).subscribe((data: any) => {
      this.todos = data;
      this.newTodoString = '';
    });
  };

  clearTodo = () => {
    this.appService.clearDoneTodo().subscribe((data: any) => {
      this.todos = data;
    });
  };

  showTodo() {
    this.appService.getTodos().subscribe((data: any) => {
      this.todos = data;
    });
  }

  handleSelected($event: any, id: string | number) {
    this.appService
      .updateTodo(id, $event.target.checked)
      .subscribe((data: any) => {
        this.todos = data;
      });
  }
}

<main>
  <h1>CodeWithSanchit</h1>
  <h2>TODO - Javascript (No Library / Framework)</h2>

  <div class="container">
    <div id="newtodo">
      <input type="text" placeholder="Enter TODO item" maxlength="50" [(ngModel)]="newTodoString" />
      <button [disabled]="!newTodoString" id="add_todo" (click)="addTodo()">ADD</button>
    </div>

    <div id="todos">
      <label class="todo" *ngFor='let todoItem of todos'>
          <input type="checkbox" id="{{todoItem.id}}" title="{{todoItem.value}}" [checked]="todoItem.status" (change)="handleSelected($event, todoItem.id)">
          <span [class.checked_item]="todoItem.status">{{todoItem.value}}</span>
      </label>
    </div>

    <button id="clear_todo" (click)="clearTodo()">CLEAR COMPLETED</button>
  </div>
</main>

// todo_reactjs/src/App.js
import { useEffect, useState } from "react";
import "./App.css";
import { TodoService } from "./todo_service.js";

function App() {
  const todoService = new TodoService("http://localhost:8080/todos");
  const [todos, setTodos] = useState([]);
  const [inputString, setInputString] = useState("");

  useEffect(() => {
    todoService.getTodos().then((response) => {
      setTodos(response);
    });
  }, []);

  return (
    <div className="App">
      <main>
        <h1>CodeWithSanchit</h1>
        <h2>TODO - Javascript (No Library / Framework)</h2>

        <div class="container">
          <div id="newtodo">
            <input
              type="text"
              placeholder="Enter TODO item"
              maxLength="50"
              value={inputString}
              onChange={(event) => {
                setInputString(event.target.value);
              }}
            />
            <button
              disabled={!inputString}
              id="add_todo"
              onClick={() => {
                todoService.addTodo(inputString).then((response) => {
                  setTodos(response);
                  setInputString("")
                });
              }}
            >
              ADD
            </button>
          </div>

          <div id="todos">
            {todos.map((todo) => {
              return (
                <div
                  class="todo"
                  data-id="${todo.id}"
                  onClick={() => {
                    todoService
                      .updateTodo(todo.id, !todo.status)
                      .then((response) => {
                        setTodos(response);
                      });
                  }}
                >
                  <input type="checkbox" id={todo.id} checked={todo.status} />
                  <span id={todo.id} className={todo.status && "checked_item"}>
                    {todo.value}
                  </span>
                </div>
              );
            })}
          </div>

          <button
            id="clear_todo"
            onClick={() => {
              todoService.clearDoneTodo().then((response) => {
                setTodos(response);
              });
            }}
          >
            CLEAR COMPLETED
          </button>
        </div>
      </main>
    </div>
  );
}

export default App;
